### ISSUE TITLE
Credentials found in this repository

### ISSUE THREAD

**Issue by d0rker** [nathanwentworth/nathanwentworth#1]
A set of credentials associated to an online host has been found inside this respository.
```
File: sftp-config.json
sha1: c5f581182cc44a537839d410212e15f4a66c882a
date: 2017-02-12T18:40:53Z
```
Consider changing your password or [not using passwords at all](https://www.digitalocean.com/community/tutorials/how-to-set-up-ssh-keys--2) and [including sensitive files in your .gitignore](https://git-scm.com/docs/gitignore)
This issue was created automatically by [GithubLeakAlert](https://github.com/misterch0c/GithubLeakAlert), excuse any false positive.<br>

Better prevent than cure (;
<p align="center">
  <img src="http://i.imgur.com/p89jk7r.png" alt="white hat pepe"/>
</p>

**Comment by nathanwentworth** [comment]
WHOOPS THANKS
